version: '3'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=file-storage-test
    ports:
      - "25432:5432"
  migration:
    build:
      context: .
      dockerfile: docker/migration/Dockerfile
    environment:
      - DATABASE_URL=postgres://root:root@postgres:5432/file-storage-test?sslmode=disable
  uploader:
    build:
      context: .
      dockerfile: docker/uploader/Dockerfile
    environment:
      - MIN_STORAGES=2
      - DATABASE_URL=postgres://root:root@postgres:5432/file-storage-test?sslmode=disable
      - REST_HOST=:9090
      - PROTOCOL_HOST=:5000
      - UPLOAD_FILE_HOST=http://127.0.0.1:19090/api/v1/upload
    ports:
      - "19090:9090"
  storage-1:
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
    environment:
      - STORAGE_ID=c4a1fa41-67fd-4df0-8596-80a18137c6bb
      - STORAGE_HOST=storage-1:5000
      - REGISTRY_HOST=uploader:5000
      - PROTOCOL_HOST=:5000
      - FS_ROOT_PATH=/tmp
  storage-2:
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
    environment:
      - STORAGE_ID=d3a984a6-bd67-4667-8b43-f5841b54ce92
      - STORAGE_HOST=storage-2:5000
      - REGISTRY_HOST=uploader:5000
      - PROTOCOL_HOST=:5000
      - FS_ROOT_PATH=/tmp
  storage-3:
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
    environment:
      - STORAGE_ID=2244cc9d-a207-41c3-b044-52b823f16939
      - STORAGE_HOST=storage-3:5000
      - REGISTRY_HOST=uploader:5000
      - PROTOCOL_HOST=:5000
      - FS_ROOT_PATH=/tmp
  storage-4:
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
    environment:
      - STORAGE_ID=df3d4dde-e07e-4b4f-abdb-aac6427dc014
      - STORAGE_HOST=storage-4:5000
      - REGISTRY_HOST=uploader:5000
      - PROTOCOL_HOST=:5000
      - FS_ROOT_PATH=/tmp
  storage-5:
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
    environment:
      - STORAGE_ID=6fc9d987-b260-4edb-a4ea-c52642b091a9
      - STORAGE_HOST=storage-5:5000
      - REGISTRY_HOST=uploader:5000
      - PROTOCOL_HOST=:5000
      - FS_ROOT_PATH=/tmp